//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("ReaPlanDBModel", "fk_ConfigjeuExercice", "ExerciceDB", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AxData.ExerciceDB), "ConfigJeuDB", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AxData.ConfigJeuDB), true)]
[assembly: EdmRelationshipAttribute("ReaPlanDBModel", "FKComposerEx_FK", "ExerciceDB", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AxData.ExerciceDB), "ParametreExDB", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AxData.ParametreExDB), true)]
[assembly: EdmRelationshipAttribute("ReaPlanDBModel", "FKFaitPasser_FK", "TherapeuteDB", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AxData.TherapeuteDB), "ExerciceDB", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AxData.ExerciceDB), true)]
[assembly: EdmRelationshipAttribute("ReaPlanDBModel", "FKJeuEx_FK", "JeuDB", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AxData.JeuDB), "ExerciceDB", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AxData.ExerciceDB), true)]
[assembly: EdmRelationshipAttribute("ReaPlanDBModel", "FKRealiser_FK", "PatientDB", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AxData.PatientDB), "ExerciceDB", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AxData.ExerciceDB), true)]
[assembly: EdmRelationshipAttribute("ReaPlanDBModel", "FKComposerJeu_FK", "JeuDB", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AxData.JeuDB), "ParametreJeuDB", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AxData.ParametreJeuDB), true)]
[assembly: EdmRelationshipAttribute("ReaPlanDBModel", "FKNomination_FK", "ParametreJeuDB", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AxData.ParametreJeuDB), "ParametreExDB", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AxData.ParametreExDB), true)]

#endregion

namespace AxData
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class ReaPlanDBEntities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet ReaPlanDBEntities à l'aide de la chaîne de connexion trouvée dans la section 'ReaPlanDBEntities' du fichier de configuration d'application.
        /// </summary>
        public ReaPlanDBEntities() : base("name=ReaPlanDBEntities", "ReaPlanDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet ReaPlanDBEntities.
        /// </summary>
        public ReaPlanDBEntities(string connectionString) : base(connectionString, "ReaPlanDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet ReaPlanDBEntities.
        /// </summary>
        public ReaPlanDBEntities(EntityConnection connection) : base(connection, "ReaPlanDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<ConfigJeuDB> ConfigJeuDBs
        {
            get
            {
                if ((_ConfigJeuDBs == null))
                {
                    _ConfigJeuDBs = base.CreateObjectSet<ConfigJeuDB>("ConfigJeuDBs");
                }
                return _ConfigJeuDBs;
            }
        }
        private ObjectSet<ConfigJeuDB> _ConfigJeuDBs;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<ExerciceDB> ExerciceDBs
        {
            get
            {
                if ((_ExerciceDBs == null))
                {
                    _ExerciceDBs = base.CreateObjectSet<ExerciceDB>("ExerciceDBs");
                }
                return _ExerciceDBs;
            }
        }
        private ObjectSet<ExerciceDB> _ExerciceDBs;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<JeuDB> JeuDBs
        {
            get
            {
                if ((_JeuDBs == null))
                {
                    _JeuDBs = base.CreateObjectSet<JeuDB>("JeuDBs");
                }
                return _JeuDBs;
            }
        }
        private ObjectSet<JeuDB> _JeuDBs;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<ParametreExDB> ParametreExDBs
        {
            get
            {
                if ((_ParametreExDBs == null))
                {
                    _ParametreExDBs = base.CreateObjectSet<ParametreExDB>("ParametreExDBs");
                }
                return _ParametreExDBs;
            }
        }
        private ObjectSet<ParametreExDB> _ParametreExDBs;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<ParametreJeuDB> ParametreJeuDBs
        {
            get
            {
                if ((_ParametreJeuDBs == null))
                {
                    _ParametreJeuDBs = base.CreateObjectSet<ParametreJeuDB>("ParametreJeuDBs");
                }
                return _ParametreJeuDBs;
            }
        }
        private ObjectSet<ParametreJeuDB> _ParametreJeuDBs;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<PatientDB> PatientDBs
        {
            get
            {
                if ((_PatientDBs == null))
                {
                    _PatientDBs = base.CreateObjectSet<PatientDB>("PatientDBs");
                }
                return _PatientDBs;
            }
        }
        private ObjectSet<PatientDB> _PatientDBs;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<TherapeuteDB> TherapeuteDBs
        {
            get
            {
                if ((_TherapeuteDBs == null))
                {
                    _TherapeuteDBs = base.CreateObjectSet<TherapeuteDB>("TherapeuteDBs");
                }
                return _TherapeuteDBs;
            }
        }
        private ObjectSet<TherapeuteDB> _TherapeuteDBs;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet ConfigJeuDBs. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToConfigJeuDBs(ConfigJeuDB configJeuDB)
        {
            base.AddObject("ConfigJeuDBs", configJeuDB);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet ExerciceDBs. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToExerciceDBs(ExerciceDB exerciceDB)
        {
            base.AddObject("ExerciceDBs", exerciceDB);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet JeuDBs. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToJeuDBs(JeuDB jeuDB)
        {
            base.AddObject("JeuDBs", jeuDB);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet ParametreExDBs. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToParametreExDBs(ParametreExDB parametreExDB)
        {
            base.AddObject("ParametreExDBs", parametreExDB);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet ParametreJeuDBs. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToParametreJeuDBs(ParametreJeuDB parametreJeuDB)
        {
            base.AddObject("ParametreJeuDBs", parametreJeuDB);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet PatientDBs. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToPatientDBs(PatientDB patientDB)
        {
            base.AddObject("PatientDBs", patientDB);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet TherapeuteDBs. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToTherapeuteDBs(TherapeuteDB therapeuteDB)
        {
            base.AddObject("TherapeuteDBs", therapeuteDB);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReaPlanDBModel", Name="ConfigJeuDB")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ConfigJeuDB : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet ConfigJeuDB.
        /// </summary>
        /// <param name="idConfig">Valeur initiale de la propriété IdConfig.</param>
        /// <param name="raideurLat">Valeur initiale de la propriété RaideurLat.</param>
        /// <param name="raideurLong">Valeur initiale de la propriété RaideurLong.</param>
        /// <param name="initialisation">Valeur initiale de la propriété Initialisation.</param>
        /// <param name="vitesse">Valeur initiale de la propriété Vitesse.</param>
        /// <param name="idExercice">Valeur initiale de la propriété IdExercice.</param>
        public static ConfigJeuDB CreateConfigJeuDB(global::System.Int32 idConfig, global::System.Int32 raideurLat, global::System.Int32 raideurLong, global::System.Int32 initialisation, global::System.Int32 vitesse, global::System.Decimal idExercice)
        {
            ConfigJeuDB configJeuDB = new ConfigJeuDB();
            configJeuDB.IdConfig = idConfig;
            configJeuDB.RaideurLat = raideurLat;
            configJeuDB.RaideurLong = raideurLong;
            configJeuDB.Initialisation = initialisation;
            configJeuDB.Vitesse = vitesse;
            configJeuDB.IdExercice = idExercice;
            return configJeuDB;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdConfig
        {
            get
            {
                return _IdConfig;
            }
            set
            {
                if (_IdConfig != value)
                {
                    OnIdConfigChanging(value);
                    ReportPropertyChanging("IdConfig");
                    _IdConfig = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdConfig");
                    OnIdConfigChanged();
                }
            }
        }
        private global::System.Int32 _IdConfig;
        partial void OnIdConfigChanging(global::System.Int32 value);
        partial void OnIdConfigChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RaideurLat
        {
            get
            {
                return _RaideurLat;
            }
            set
            {
                OnRaideurLatChanging(value);
                ReportPropertyChanging("RaideurLat");
                _RaideurLat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RaideurLat");
                OnRaideurLatChanged();
            }
        }
        private global::System.Int32 _RaideurLat;
        partial void OnRaideurLatChanging(global::System.Int32 value);
        partial void OnRaideurLatChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RaideurLong
        {
            get
            {
                return _RaideurLong;
            }
            set
            {
                OnRaideurLongChanging(value);
                ReportPropertyChanging("RaideurLong");
                _RaideurLong = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RaideurLong");
                OnRaideurLongChanged();
            }
        }
        private global::System.Int32 _RaideurLong;
        partial void OnRaideurLongChanging(global::System.Int32 value);
        partial void OnRaideurLongChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Initialisation
        {
            get
            {
                return _Initialisation;
            }
            set
            {
                OnInitialisationChanging(value);
                ReportPropertyChanging("Initialisation");
                _Initialisation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Initialisation");
                OnInitialisationChanged();
            }
        }
        private global::System.Int32 _Initialisation;
        partial void OnInitialisationChanging(global::System.Int32 value);
        partial void OnInitialisationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Vitesse
        {
            get
            {
                return _Vitesse;
            }
            set
            {
                OnVitesseChanging(value);
                ReportPropertyChanging("Vitesse");
                _Vitesse = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Vitesse");
                OnVitesseChanged();
            }
        }
        private global::System.Int32 _Vitesse;
        partial void OnVitesseChanging(global::System.Int32 value);
        partial void OnVitesseChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal IdExercice
        {
            get
            {
                return _IdExercice;
            }
            set
            {
                OnIdExerciceChanging(value);
                ReportPropertyChanging("IdExercice");
                _IdExercice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdExercice");
                OnIdExerciceChanged();
            }
        }
        private global::System.Decimal _IdExercice;
        partial void OnIdExerciceChanging(global::System.Decimal value);
        partial void OnIdExerciceChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReaPlanDBModel", "fk_ConfigjeuExercice", "ExerciceDB")]
        public ExerciceDB ExerciceDB
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ExerciceDB>("ReaPlanDBModel.fk_ConfigjeuExercice", "ExerciceDB").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ExerciceDB>("ReaPlanDBModel.fk_ConfigjeuExercice", "ExerciceDB").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ExerciceDB> ExerciceDBReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ExerciceDB>("ReaPlanDBModel.fk_ConfigjeuExercice", "ExerciceDB");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ExerciceDB>("ReaPlanDBModel.fk_ConfigjeuExercice", "ExerciceDB", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReaPlanDBModel", Name="ExerciceDB")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ExerciceDB : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet ExerciceDB.
        /// </summary>
        /// <param name="idExercice">Valeur initiale de la propriété IdExercice.</param>
        /// <param name="date">Valeur initiale de la propriété Date.</param>
        /// <param name="heure">Valeur initiale de la propriété Heure.</param>
        /// <param name="idPatient">Valeur initiale de la propriété IdPatient.</param>
        /// <param name="idJeu">Valeur initiale de la propriété IdJeu.</param>
        /// <param name="idUtilisateur">Valeur initiale de la propriété IdUtilisateur.</param>
        public static ExerciceDB CreateExerciceDB(global::System.Decimal idExercice, global::System.DateTime date, global::System.TimeSpan heure, global::System.Decimal idPatient, global::System.Decimal idJeu, global::System.Decimal idUtilisateur)
        {
            ExerciceDB exerciceDB = new ExerciceDB();
            exerciceDB.IdExercice = idExercice;
            exerciceDB.Date = date;
            exerciceDB.Heure = heure;
            exerciceDB.IdPatient = idPatient;
            exerciceDB.IdJeu = idJeu;
            exerciceDB.IdUtilisateur = idUtilisateur;
            return exerciceDB;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal IdExercice
        {
            get
            {
                return _IdExercice;
            }
            set
            {
                if (_IdExercice != value)
                {
                    OnIdExerciceChanging(value);
                    ReportPropertyChanging("IdExercice");
                    _IdExercice = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdExercice");
                    OnIdExerciceChanged();
                }
            }
        }
        private global::System.Decimal _IdExercice;
        partial void OnIdExerciceChanging(global::System.Decimal value);
        partial void OnIdExerciceChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan Heure
        {
            get
            {
                return _Heure;
            }
            set
            {
                OnHeureChanging(value);
                ReportPropertyChanging("Heure");
                _Heure = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Heure");
                OnHeureChanged();
            }
        }
        private global::System.TimeSpan _Heure;
        partial void OnHeureChanging(global::System.TimeSpan value);
        partial void OnHeureChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal IdPatient
        {
            get
            {
                return _IdPatient;
            }
            set
            {
                OnIdPatientChanging(value);
                ReportPropertyChanging("IdPatient");
                _IdPatient = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdPatient");
                OnIdPatientChanged();
            }
        }
        private global::System.Decimal _IdPatient;
        partial void OnIdPatientChanging(global::System.Decimal value);
        partial void OnIdPatientChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal IdJeu
        {
            get
            {
                return _IdJeu;
            }
            set
            {
                OnIdJeuChanging(value);
                ReportPropertyChanging("IdJeu");
                _IdJeu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdJeu");
                OnIdJeuChanged();
            }
        }
        private global::System.Decimal _IdJeu;
        partial void OnIdJeuChanging(global::System.Decimal value);
        partial void OnIdJeuChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal IdUtilisateur
        {
            get
            {
                return _IdUtilisateur;
            }
            set
            {
                OnIdUtilisateurChanging(value);
                ReportPropertyChanging("IdUtilisateur");
                _IdUtilisateur = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdUtilisateur");
                OnIdUtilisateurChanged();
            }
        }
        private global::System.Decimal _IdUtilisateur;
        partial void OnIdUtilisateurChanging(global::System.Decimal value);
        partial void OnIdUtilisateurChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReaPlanDBModel", "fk_ConfigjeuExercice", "ConfigJeuDB")]
        public EntityCollection<ConfigJeuDB> ConfigJeuDBs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ConfigJeuDB>("ReaPlanDBModel.fk_ConfigjeuExercice", "ConfigJeuDB");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ConfigJeuDB>("ReaPlanDBModel.fk_ConfigjeuExercice", "ConfigJeuDB", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReaPlanDBModel", "FKComposerEx_FK", "ParametreExDB")]
        public EntityCollection<ParametreExDB> ParametreExDBs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ParametreExDB>("ReaPlanDBModel.FKComposerEx_FK", "ParametreExDB");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ParametreExDB>("ReaPlanDBModel.FKComposerEx_FK", "ParametreExDB", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReaPlanDBModel", "FKFaitPasser_FK", "TherapeuteDB")]
        public TherapeuteDB TherapeuteDB
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TherapeuteDB>("ReaPlanDBModel.FKFaitPasser_FK", "TherapeuteDB").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TherapeuteDB>("ReaPlanDBModel.FKFaitPasser_FK", "TherapeuteDB").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TherapeuteDB> TherapeuteDBReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TherapeuteDB>("ReaPlanDBModel.FKFaitPasser_FK", "TherapeuteDB");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TherapeuteDB>("ReaPlanDBModel.FKFaitPasser_FK", "TherapeuteDB", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReaPlanDBModel", "FKJeuEx_FK", "JeuDB")]
        public JeuDB JeuDB
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<JeuDB>("ReaPlanDBModel.FKJeuEx_FK", "JeuDB").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<JeuDB>("ReaPlanDBModel.FKJeuEx_FK", "JeuDB").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<JeuDB> JeuDBReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<JeuDB>("ReaPlanDBModel.FKJeuEx_FK", "JeuDB");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<JeuDB>("ReaPlanDBModel.FKJeuEx_FK", "JeuDB", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReaPlanDBModel", "FKRealiser_FK", "PatientDB")]
        public PatientDB PatientDB
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PatientDB>("ReaPlanDBModel.FKRealiser_FK", "PatientDB").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PatientDB>("ReaPlanDBModel.FKRealiser_FK", "PatientDB").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PatientDB> PatientDBReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PatientDB>("ReaPlanDBModel.FKRealiser_FK", "PatientDB");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PatientDB>("ReaPlanDBModel.FKRealiser_FK", "PatientDB", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReaPlanDBModel", Name="JeuDB")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class JeuDB : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet JeuDB.
        /// </summary>
        /// <param name="idJeu">Valeur initiale de la propriété IdJeu.</param>
        /// <param name="nomJeu">Valeur initiale de la propriété NomJeu.</param>
        public static JeuDB CreateJeuDB(global::System.Decimal idJeu, global::System.String nomJeu)
        {
            JeuDB jeuDB = new JeuDB();
            jeuDB.IdJeu = idJeu;
            jeuDB.NomJeu = nomJeu;
            return jeuDB;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal IdJeu
        {
            get
            {
                return _IdJeu;
            }
            set
            {
                if (_IdJeu != value)
                {
                    OnIdJeuChanging(value);
                    ReportPropertyChanging("IdJeu");
                    _IdJeu = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdJeu");
                    OnIdJeuChanged();
                }
            }
        }
        private global::System.Decimal _IdJeu;
        partial void OnIdJeuChanging(global::System.Decimal value);
        partial void OnIdJeuChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NomJeu
        {
            get
            {
                return _NomJeu;
            }
            set
            {
                OnNomJeuChanging(value);
                ReportPropertyChanging("NomJeu");
                _NomJeu = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NomJeu");
                OnNomJeuChanged();
            }
        }
        private global::System.String _NomJeu;
        partial void OnNomJeuChanging(global::System.String value);
        partial void OnNomJeuChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReaPlanDBModel", "FKJeuEx_FK", "ExerciceDB")]
        public EntityCollection<ExerciceDB> ExerciceDBs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ExerciceDB>("ReaPlanDBModel.FKJeuEx_FK", "ExerciceDB");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ExerciceDB>("ReaPlanDBModel.FKJeuEx_FK", "ExerciceDB", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReaPlanDBModel", "FKComposerJeu_FK", "ParametreJeuDB")]
        public EntityCollection<ParametreJeuDB> ParametreJeuDBs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ParametreJeuDB>("ReaPlanDBModel.FKComposerJeu_FK", "ParametreJeuDB");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ParametreJeuDB>("ReaPlanDBModel.FKComposerJeu_FK", "ParametreJeuDB", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReaPlanDBModel", Name="ParametreExDB")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ParametreExDB : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet ParametreExDB.
        /// </summary>
        /// <param name="idParametreExEvaluation">Valeur initiale de la propriété IdParametreExEvaluation.</param>
        /// <param name="resultat">Valeur initiale de la propriété Resultat.</param>
        /// <param name="idExercice">Valeur initiale de la propriété IdExercice.</param>
        /// <param name="idParametreJeuDB">Valeur initiale de la propriété IdParametreJeuDB.</param>
        public static ParametreExDB CreateParametreExDB(global::System.Decimal idParametreExEvaluation, global::System.Decimal resultat, global::System.Decimal idExercice, global::System.Decimal idParametreJeuDB)
        {
            ParametreExDB parametreExDB = new ParametreExDB();
            parametreExDB.IdParametreExEvaluation = idParametreExEvaluation;
            parametreExDB.Resultat = resultat;
            parametreExDB.IdExercice = idExercice;
            parametreExDB.IdParametreJeuDB = idParametreJeuDB;
            return parametreExDB;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal IdParametreExEvaluation
        {
            get
            {
                return _IdParametreExEvaluation;
            }
            set
            {
                if (_IdParametreExEvaluation != value)
                {
                    OnIdParametreExEvaluationChanging(value);
                    ReportPropertyChanging("IdParametreExEvaluation");
                    _IdParametreExEvaluation = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdParametreExEvaluation");
                    OnIdParametreExEvaluationChanged();
                }
            }
        }
        private global::System.Decimal _IdParametreExEvaluation;
        partial void OnIdParametreExEvaluationChanging(global::System.Decimal value);
        partial void OnIdParametreExEvaluationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Resultat
        {
            get
            {
                return _Resultat;
            }
            set
            {
                OnResultatChanging(value);
                ReportPropertyChanging("Resultat");
                _Resultat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Resultat");
                OnResultatChanged();
            }
        }
        private global::System.Decimal _Resultat;
        partial void OnResultatChanging(global::System.Decimal value);
        partial void OnResultatChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> EcartType
        {
            get
            {
                return _EcartType;
            }
            set
            {
                OnEcartTypeChanging(value);
                ReportPropertyChanging("EcartType");
                _EcartType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EcartType");
                OnEcartTypeChanged();
            }
        }
        private Nullable<global::System.Decimal> _EcartType;
        partial void OnEcartTypeChanging(Nullable<global::System.Decimal> value);
        partial void OnEcartTypeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CoefficientVariation
        {
            get
            {
                return _CoefficientVariation;
            }
            set
            {
                OnCoefficientVariationChanging(value);
                ReportPropertyChanging("CoefficientVariation");
                _CoefficientVariation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CoefficientVariation");
                OnCoefficientVariationChanged();
            }
        }
        private Nullable<global::System.Decimal> _CoefficientVariation;
        partial void OnCoefficientVariationChanging(Nullable<global::System.Decimal> value);
        partial void OnCoefficientVariationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal IdExercice
        {
            get
            {
                return _IdExercice;
            }
            set
            {
                OnIdExerciceChanging(value);
                ReportPropertyChanging("IdExercice");
                _IdExercice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdExercice");
                OnIdExerciceChanged();
            }
        }
        private global::System.Decimal _IdExercice;
        partial void OnIdExerciceChanging(global::System.Decimal value);
        partial void OnIdExerciceChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal IdParametreJeuDB
        {
            get
            {
                return _IdParametreJeuDB;
            }
            set
            {
                OnIdParametreJeuDBChanging(value);
                ReportPropertyChanging("IdParametreJeuDB");
                _IdParametreJeuDB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdParametreJeuDB");
                OnIdParametreJeuDBChanged();
            }
        }
        private global::System.Decimal _IdParametreJeuDB;
        partial void OnIdParametreJeuDBChanging(global::System.Decimal value);
        partial void OnIdParametreJeuDBChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReaPlanDBModel", "FKComposerEx_FK", "ExerciceDB")]
        public ExerciceDB ExerciceDB
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ExerciceDB>("ReaPlanDBModel.FKComposerEx_FK", "ExerciceDB").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ExerciceDB>("ReaPlanDBModel.FKComposerEx_FK", "ExerciceDB").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ExerciceDB> ExerciceDBReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ExerciceDB>("ReaPlanDBModel.FKComposerEx_FK", "ExerciceDB");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ExerciceDB>("ReaPlanDBModel.FKComposerEx_FK", "ExerciceDB", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReaPlanDBModel", "FKNomination_FK", "ParametreJeuDB")]
        public ParametreJeuDB ParametreJeuDB
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ParametreJeuDB>("ReaPlanDBModel.FKNomination_FK", "ParametreJeuDB").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ParametreJeuDB>("ReaPlanDBModel.FKNomination_FK", "ParametreJeuDB").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ParametreJeuDB> ParametreJeuDBReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ParametreJeuDB>("ReaPlanDBModel.FKNomination_FK", "ParametreJeuDB");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ParametreJeuDB>("ReaPlanDBModel.FKNomination_FK", "ParametreJeuDB", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReaPlanDBModel", Name="ParametreJeuDB")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ParametreJeuDB : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet ParametreJeuDB.
        /// </summary>
        /// <param name="idParametreJeuDB">Valeur initiale de la propriété IdParametreJeuDB.</param>
        /// <param name="libelleParametre">Valeur initiale de la propriété LibelleParametre.</param>
        /// <param name="yo">Valeur initiale de la propriété Yo.</param>
        /// <param name="constanteA">Valeur initiale de la propriété ConstanteA.</param>
        /// <param name="deviationStandard">Valeur initiale de la propriété DeviationStandard.</param>
        /// <param name="idJeu">Valeur initiale de la propriété IdJeu.</param>
        public static ParametreJeuDB CreateParametreJeuDB(global::System.Decimal idParametreJeuDB, global::System.String libelleParametre, global::System.Decimal yo, global::System.Decimal constanteA, global::System.Decimal deviationStandard, global::System.Decimal idJeu)
        {
            ParametreJeuDB parametreJeuDB = new ParametreJeuDB();
            parametreJeuDB.IdParametreJeuDB = idParametreJeuDB;
            parametreJeuDB.LibelleParametre = libelleParametre;
            parametreJeuDB.Yo = yo;
            parametreJeuDB.ConstanteA = constanteA;
            parametreJeuDB.DeviationStandard = deviationStandard;
            parametreJeuDB.IdJeu = idJeu;
            return parametreJeuDB;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal IdParametreJeuDB
        {
            get
            {
                return _IdParametreJeuDB;
            }
            set
            {
                if (_IdParametreJeuDB != value)
                {
                    OnIdParametreJeuDBChanging(value);
                    ReportPropertyChanging("IdParametreJeuDB");
                    _IdParametreJeuDB = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdParametreJeuDB");
                    OnIdParametreJeuDBChanged();
                }
            }
        }
        private global::System.Decimal _IdParametreJeuDB;
        partial void OnIdParametreJeuDBChanging(global::System.Decimal value);
        partial void OnIdParametreJeuDBChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LibelleParametre
        {
            get
            {
                return _LibelleParametre;
            }
            set
            {
                OnLibelleParametreChanging(value);
                ReportPropertyChanging("LibelleParametre");
                _LibelleParametre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LibelleParametre");
                OnLibelleParametreChanged();
            }
        }
        private global::System.String _LibelleParametre;
        partial void OnLibelleParametreChanging(global::System.String value);
        partial void OnLibelleParametreChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Yo
        {
            get
            {
                return _Yo;
            }
            set
            {
                OnYoChanging(value);
                ReportPropertyChanging("Yo");
                _Yo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Yo");
                OnYoChanged();
            }
        }
        private global::System.Decimal _Yo;
        partial void OnYoChanging(global::System.Decimal value);
        partial void OnYoChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ConstanteA
        {
            get
            {
                return _ConstanteA;
            }
            set
            {
                OnConstanteAChanging(value);
                ReportPropertyChanging("ConstanteA");
                _ConstanteA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConstanteA");
                OnConstanteAChanged();
            }
        }
        private global::System.Decimal _ConstanteA;
        partial void OnConstanteAChanging(global::System.Decimal value);
        partial void OnConstanteAChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal DeviationStandard
        {
            get
            {
                return _DeviationStandard;
            }
            set
            {
                OnDeviationStandardChanging(value);
                ReportPropertyChanging("DeviationStandard");
                _DeviationStandard = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeviationStandard");
                OnDeviationStandardChanged();
            }
        }
        private global::System.Decimal _DeviationStandard;
        partial void OnDeviationStandardChanging(global::System.Decimal value);
        partial void OnDeviationStandardChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal IdJeu
        {
            get
            {
                return _IdJeu;
            }
            set
            {
                OnIdJeuChanging(value);
                ReportPropertyChanging("IdJeu");
                _IdJeu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdJeu");
                OnIdJeuChanged();
            }
        }
        private global::System.Decimal _IdJeu;
        partial void OnIdJeuChanging(global::System.Decimal value);
        partial void OnIdJeuChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReaPlanDBModel", "FKComposerJeu_FK", "JeuDB")]
        public JeuDB JeuDB
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<JeuDB>("ReaPlanDBModel.FKComposerJeu_FK", "JeuDB").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<JeuDB>("ReaPlanDBModel.FKComposerJeu_FK", "JeuDB").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<JeuDB> JeuDBReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<JeuDB>("ReaPlanDBModel.FKComposerJeu_FK", "JeuDB");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<JeuDB>("ReaPlanDBModel.FKComposerJeu_FK", "JeuDB", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReaPlanDBModel", "FKNomination_FK", "ParametreExDB")]
        public EntityCollection<ParametreExDB> ParametreExDBs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ParametreExDB>("ReaPlanDBModel.FKNomination_FK", "ParametreExDB");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ParametreExDB>("ReaPlanDBModel.FKNomination_FK", "ParametreExDB", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReaPlanDBModel", Name="PatientDB")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PatientDB : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet PatientDB.
        /// </summary>
        /// <param name="idPatient">Valeur initiale de la propriété IdPatient.</param>
        /// <param name="nom">Valeur initiale de la propriété Nom.</param>
        /// <param name="prenom">Valeur initiale de la propriété Prenom.</param>
        /// <param name="dateNaissance">Valeur initiale de la propriété DateNaissance.</param>
        /// <param name="sexe">Valeur initiale de la propriété Sexe.</param>
        /// <param name="taille">Valeur initiale de la propriété Taille.</param>
        /// <param name="poids">Valeur initiale de la propriété Poids.</param>
        /// <param name="id1">Valeur initiale de la propriété Id1.</param>
        /// <param name="id2">Valeur initiale de la propriété Id2.</param>
        /// <param name="nationalite">Valeur initiale de la propriété Nationalite.</param>
        public static PatientDB CreatePatientDB(global::System.String nom, global::System.String prenom, global::System.DateTime dateNaissance, global::System.String sexe, global::System.Decimal taille, global::System.Decimal poids, global::System.Decimal id1, global::System.Decimal id2)
        {
            PatientDB patientDB = new PatientDB();
            patientDB.Nom = nom;
            patientDB.Prenom = prenom;
            patientDB.DateNaissance = dateNaissance;
            patientDB.Sexe = sexe;
            patientDB.Taille = taille;
            patientDB.Poids = poids;
            patientDB.Id1 = id1;
            patientDB.Id2 = id2;
            patientDB.Nationalite = "BELGIAN";
            return patientDB;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal IdPatient
        {
            get
            {
                return _IdPatient;
            }
            set
            {
                if (_IdPatient != value)
                {
                    OnIdPatientChanging(value);
                    ReportPropertyChanging("IdPatient");
                    _IdPatient = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdPatient");
                    OnIdPatientChanged();
                }
            }
        }
        private global::System.Decimal _IdPatient;
        partial void OnIdPatientChanging(global::System.Decimal value);
        partial void OnIdPatientChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Prenom
        {
            get
            {
                return _Prenom;
            }
            set
            {
                OnPrenomChanging(value);
                ReportPropertyChanging("Prenom");
                _Prenom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Prenom");
                OnPrenomChanged();
            }
        }
        private global::System.String _Prenom;
        partial void OnPrenomChanging(global::System.String value);
        partial void OnPrenomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateNaissance
        {
            get
            {
                return _DateNaissance;
            }
            set
            {
                OnDateNaissanceChanging(value);
                ReportPropertyChanging("DateNaissance");
                _DateNaissance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateNaissance");
                OnDateNaissanceChanged();
            }
        }
        private global::System.DateTime _DateNaissance;
        partial void OnDateNaissanceChanging(global::System.DateTime value);
        partial void OnDateNaissanceChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sexe
        {
            get
            {
                return _Sexe;
            }
            set
            {
                OnSexeChanging(value);
                ReportPropertyChanging("Sexe");
                _Sexe = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sexe");
                OnSexeChanged();
            }
        }
        private global::System.String _Sexe;
        partial void OnSexeChanging(global::System.String value);
        partial void OnSexeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Taille
        {
            get
            {
                return _Taille;
            }
            set
            {
                OnTailleChanging(value);
                ReportPropertyChanging("Taille");
                _Taille = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Taille");
                OnTailleChanged();
            }
        }
        private global::System.Decimal _Taille;
        partial void OnTailleChanging(global::System.Decimal value);
        partial void OnTailleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Poids
        {
            get
            {
                return _Poids;
            }
            set
            {
                OnPoidsChanging(value);
                ReportPropertyChanging("Poids");
                _Poids = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Poids");
                OnPoidsChanged();
            }
        }
        private global::System.Decimal _Poids;
        partial void OnPoidsChanging(global::System.Decimal value);
        partial void OnPoidsChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Id1
        {
            get
            {
                return _Id1;
            }
            set
            {
                OnId1Changing(value);
                ReportPropertyChanging("Id1");
                _Id1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id1");
                OnId1Changed();
            }
        }
        private global::System.Decimal _Id1;
        partial void OnId1Changing(global::System.Decimal value);
        partial void OnId1Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Id2
        {
            get
            {
                return _Id2;
            }
            set
            {
                OnId2Changing(value);
                ReportPropertyChanging("Id2");
                _Id2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id2");
                OnId2Changed();
            }
        }
        private global::System.Decimal _Id2;
        partial void OnId2Changing(global::System.Decimal value);
        partial void OnId2Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nationalite
        {
            get
            {
                return _Nationalite;
            }
            set
            {
                OnNationaliteChanging(value);
                ReportPropertyChanging("Nationalite");
                _Nationalite = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nationalite");
                OnNationaliteChanged();
            }
        }
        private global::System.String _Nationalite;
        partial void OnNationaliteChanging(global::System.String value);
        partial void OnNationaliteChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReaPlanDBModel", "FKRealiser_FK", "ExerciceDB")]
        public EntityCollection<ExerciceDB> ExerciceDBs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ExerciceDB>("ReaPlanDBModel.FKRealiser_FK", "ExerciceDB");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ExerciceDB>("ReaPlanDBModel.FKRealiser_FK", "ExerciceDB", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ReaPlanDBModel", Name="TherapeuteDB")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TherapeuteDB : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet TherapeuteDB.
        /// </summary>
        /// <param name="idUtilisateur">Valeur initiale de la propriété IdUtilisateur.</param>
        /// <param name="nom">Valeur initiale de la propriété Nom.</param>
        /// <param name="prenom">Valeur initiale de la propriété Prenom.</param>
        /// <param name="login">Valeur initiale de la propriété Login.</param>
        /// <param name="motDePasse">Valeur initiale de la propriété MotDePasse.</param>
        /// <param name="administrateur">Valeur initiale de la propriété Administrateur.</param>
        public static TherapeuteDB CreateTherapeuteDB(global::System.String nom, global::System.String prenom, global::System.String login, global::System.String motDePasse)
        {
            TherapeuteDB therapeuteDB = new TherapeuteDB();
            therapeuteDB.Nom = nom;
            therapeuteDB.Prenom = prenom;
            therapeuteDB.Login = login;
            therapeuteDB.MotDePasse = motDePasse;
            return therapeuteDB;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal IdUtilisateur
        {
            get
            {
                return _IdUtilisateur;
            }
            set
            {
                if (_IdUtilisateur != value)
                {
                    OnIdUtilisateurChanging(value);
                    ReportPropertyChanging("IdUtilisateur");
                    _IdUtilisateur = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdUtilisateur");
                    OnIdUtilisateurChanged();
                }
            }
        }
        private global::System.Decimal _IdUtilisateur;
        partial void OnIdUtilisateurChanging(global::System.Decimal value);
        partial void OnIdUtilisateurChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Prenom
        {
            get
            {
                return _Prenom;
            }
            set
            {
                OnPrenomChanging(value);
                ReportPropertyChanging("Prenom");
                _Prenom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Prenom");
                OnPrenomChanged();
            }
        }
        private global::System.String _Prenom;
        partial void OnPrenomChanging(global::System.String value);
        partial void OnPrenomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MotDePasse
        {
            get
            {
                return _MotDePasse;
            }
            set
            {
                OnMotDePasseChanging(value);
                ReportPropertyChanging("MotDePasse");
                _MotDePasse = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MotDePasse");
                OnMotDePasseChanged();
            }
        }
        private global::System.String _MotDePasse;
        partial void OnMotDePasseChanging(global::System.String value);
        partial void OnMotDePasseChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Administrateur
        {
            get
            {
                return _Administrateur;
            }
            set
            {
                OnAdministrateurChanging(value);
                ReportPropertyChanging("Administrateur");
                _Administrateur = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Administrateur");
                OnAdministrateurChanged();
            }
        }
        private global::System.Boolean _Administrateur;
        partial void OnAdministrateurChanging(global::System.Boolean value);
        partial void OnAdministrateurChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ReaPlanDBModel", "FKFaitPasser_FK", "ExerciceDB")]
        public EntityCollection<ExerciceDB> ExerciceDBs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ExerciceDB>("ReaPlanDBModel.FKFaitPasser_FK", "ExerciceDB");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ExerciceDB>("ReaPlanDBModel.FKFaitPasser_FK", "ExerciceDB", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
